

<div class="row" style="margin-left: 130px; margin-top: 260px;">
    <div class="col-lg-6">
        <form role="form" action="novo" method="post"  class="form form-group" id="">
            <div class="form-group">
                <label class="label label-info" value="<?php if (isset($this->dados['nome'])) print $this->dados['nome']; ?>">Nome</label>
                <input type="text" name="nome" class="form-control" />
                <input type="hidden" name="guardar" value="1" />
            </div>
            <div class="form-group">
                <label class="label label-info">Descrição</label> 
                <input type="text" name="comentario" class="form-control" value="<?php if (isset($this->dados['comentario'])) print $this->dados['comentario']; ?>"/>
            </div>

                 
            <div class="form-group"><button  type="submit"class="btn btn-success"><i class="glyphicon glyphicon-saved">Novo</i></button></div>
        </form>
    </div>
</div>