<div class="panel-body">
    <br />
    <br />
    <hr>

    <?php if (Session::nivelViewRestrito(array('admin'))): ?>
        <a href="<?php URL . print $this->link; ?>">Novo</a>
    <?php endif; ?>
 <?php if (isset($this->categoria)&& !empty($this->categoria)): ?>
    <table class="table  table-condensed table-hover table-striped table-bordered">

        <thead>
            <tr>
                <th>Categorias</th> 
                <th>Descrição</th> 
                <th>Imagem</th>
                <th>Alterar</th>
                <th>Apagar</th>
            </tr>
        </thead>

        <tbody>
           
                <?php foreach ($this->categoria as $valor): ?>
                    <tr>
                        <td><?php print $valor['nome']; ?></td>
                        <td><?php print $valor['descricao']; ?></td>
                        <td><img src="<?php $_SERVER['DOCUMENT_ROOT'].DS."public".DS."img".DS."categoria".DS."img".DS.$valor['img'] ?>" alt="imagem" /></td>
                        <td><a rel="<?php print $valor['id_categoria']; ?>" href="<?php print URL . "categoria/editar/" . $valor['id_categoria']; ?>" id="altera"><i class="glyphicon glyphicon-pencil">Alterar</i></a></td>
                        <td><a rel="<?php print $valor['id_categoria']; ?>" href="<?php print URL . "categoria/apagar/" . $valor['id_categoria']; ?>" id="delete"><i class="glyphicon glyphicon-trash">Apagar</i></a></td>
                    </tr>
               <?php endforeach; ?>
                   
            </tbody>
         </table>
        <?php else: ?>
            <h2>Não existe nenhuma categoria cadastrada</h2>
         <?php endif; ?>
   
</div>
<ul class="pagination">
    <li><?php if (isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?></li>
</ul>

  
