
<br /><br /><br />
    <section class="col-sm-6">
        
        <section id="cd-timeline" class="cd-container">
            <?php if (isset($this->tutorial)): ?>
            
            <?php  foreach ($this->tutorial as $d): ?>
                <div class="cd-timeline-block">
                    <div class="cd-timeline-img cd-picture"> <img src="public/img/cd-icon-picture.svg" alt="Picture"> </div>
                    <!-- cd-timeline-img -->

                    <div class="cd-timeline-content">
                        <h2><?php print $d['titulo']; ?></h2>
                        <p> <?php print $d['descricao']; ?> .</p>
                        <a href="#0" class="cd-read-more">Leia Mais</a> <span class="cd-date">Jan 14</span> </div>
                    <!-- cd-timeline-content --> 
                </div>
                <!-- cd-timeline-block -->
            
                    <?php endforeach; ?>
                <?php endif;?>
            <!-- cd-timeline-block --> 
        </section>


    </section>


    <section class="col-sm-6">

        <section id="cd-timeline" class="cd-container">
            <?php if (isset($this->tutorial)): ?>
            <?php  foreach ($this->tutorial as $d): ?>
                <div class="cd-timeline-block">
                    <div class="cd-timeline-img cd-picture"> <img src="public/img/cd-icon-picture.svg" alt="Picture"> </div>
                    <!-- cd-timeline-img -->

                    <div class="cd-timeline-content">
                        <h2><?php print $d['titulo']; ?></h2>
                        <p> <?php print $d['descricao']; ?> .</p>
                        <a href="#0" class="cd-read-more">Leia Mais</a> <span class="cd-date">Jan 14</span> </div>
                    <!-- cd-timeline-content --> 
                </div>
                <!-- cd-timeline-block -->
            
                    <?php endforeach; ?>
                <?php endif;?>
            <!-- cd-timeline-block --> 
        </section>


    </section>
    <!-----FIM DO Panel Central----->
<ul class="pagination">
    <li><?php if (isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?></li>
</ul>