<div class="panel-body">
    <hr>
    

    <?php if (isset($this->usuarios) && !empty($this->usuarios)): ?>
        <table class="table  table-condensed table-hover table-striped table-bordered">

            <thead>
                <tr>
                    <th>Usuarios</th> 
                    <th>Nome</th> 
                    <th>Email</th>
                    <th>Alterar</th>
                    <th>Apagar</th>
                </tr>
            </thead>

            <tbody>

                <?php foreach ($this->usuarios as $valor): ?>
                    <tr>
                        <td><?php print $valor['usuario']; ?></td>
                        <td><?php print $valor['email']; ?></td>

                        <td><a rel="<?php print $valor['id_usuario']; ?>" href="<?php print URL . "usuario/editar/" . $valor['id_usuario']; ?>" id="altera"><i class="glyphicon glyphicon-pencil">Alterar</i></a></td>
                        <td><a rel="<?php print $valor['id_usuario']; ?>" href="<?php print URL . "usuario/apagar/" . $valor['usuario']; ?>" id="delete"><i class="glyphicon glyphicon-trash">Apagar</i></a></td>
                    </tr>
                <?php endforeach; ?>

            </tbody>
        </table>
    <?php else: ?>
        <h2>Não existe nenhuma usuario cadastrado</h2>
    <?php endif; ?>

</div>
<ul class="pagination">
    <li><?php if (isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?></li>
</ul>