<br /><br />
<div class="container">

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <form role="form" method="POST" action="<?php print URL."registrar";?>">
			<h2>Registra-se Porfavor <small>Nossos Serviços São Gratis.</small></h2>
			<hr class="colorgraph">
			<div class="row">
		<div class="col-xs-6 col-sm-6 col-md-6">
		<div class="form-group">
                    <input type="text" name="p_nome" id="p_nome" class="form-control input-lg" placeholder="Peixe" tabindex="1" value="<?php if(isset($this->dados)) print $this->dados['p_nome'];?>">
		</div>
		</div>
		<div class="col-xs-6 col-sm-6 col-md-6">
		<div class="form-group">
		<input type="text" name="u_nome" id="u_nome" class="form-control input-lg" placeholder="Sam" tabindex="2" <?php if(isset($this->dados)) print $this->dados['u_nome'];?>>
		</div>
		</div>
	        </div>
	       <div class="form-group">
                   <input type="text" name="usuario" id="usuario" class="form-control input-lg" placeholder="Samengenner" tabindex="3" value="<?php if(isset($this->dados)) print $this->dados['usuario'];?>">
		</div>
		<div class="form-group">
		<input type="email" name="email" id="email" class="form-control input-lg" placeholder="teste@teste.com" tabindex="4" <?php if(isset($this->dados)) print $this->dados['email'];?>>
		</div>
		<div class="row">
		<div class="col-xs-6 col-sm-6 col-md-6">
		<div class="form-group">
                    <input type="password" name="senha" id="password" class="form-control input-lg" placeholder="Senha" tabindex="5" value="<?php if(isset($this->dados)) print $this->dados['senha'];?>">
		</div>
		</div>
	        <div class="col-xs-6 col-sm-6 col-md-6">
		<div class="form-group">
                    <input type="password" name="c_senha" id="password_confirmation" class="form-control input-lg" placeholder="Confirmar Senha" tabindex="6" value="<?php if(isset($this->dados)) print $this->dados['c_senha'];?>">
		</div>
		</div>
		</div>
		<div class="row">
		<div class="col-xs-3 col-sm-3 col-md-3">
		</div>
		<div class="col-xs-9 col-sm-9 col-md-9">
					 clica em registrar <strong class="label label-primary">Registrar</strong>, Agrega-se a Nós <a href="#" data-toggle="modal" data-target="#t_and_c_m">Termos e Condições</a> Aceita os Cookie, e inclui no seu navegador.
		</div>
		</div>
			
		<hr class="colorgraph">
                <input type="hidden" name="enviar" value="1" />
			<div class="row">
				<div class="col-xs-6 col-md-6"><input type="submit" value="Registrar" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
				<div class="col-xs-6 col-md-6"><a href="<?php print URL."login"; ?>" class="btn btn-success btn-block btn-lg">Login</a></div>
			</div>
		</form>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">Termos & Condições</h4>
			</div>
			<div class="modal-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Eu Aceito</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

